services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-slowquery-lab
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ./postgres-logs:/var/log/postgresql
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.track=all
      - -c
      - pg_stat_statements.max=10000
      - -c
      - log_statement=all
      - -c
      - log_duration=on
      - -c
      - log_min_duration_statement=100
      - -c
      - log_line_prefix=%t [%p] %u@%d
      - -c
      - log_checkpoints=on
      - -c
      - log_connections=on
      - -c
      - log_disconnections=on
      - -c
      - log_lock_waits=on
      - -c
      - log_temp_files=0
      - -c
      - log_autovacuum_min_duration=0
      - -c
      - shared_buffers=256MB
      - -c
      - work_mem=4MB
      - -c
      - maintenance_work_mem=64MB
      - -c
      - effective_cache_size=1GB
      - -c
      - random_page_cost=1.1
      - -c
      - track_io_timing=on
      - -c
      - log_destination=stderr
      - -c
      - logging_collector=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: